time:
    start_date: 2020-01-01_00:00:00
    end_date:   2020-01-01_06:00:00
    interval_seconds: 10800

geogrid:
    max_dom: 3
    dx: 27000
    dy: 27000
    map_proj: lambert
    ref_lat: 55.45
    ref_lon: 37.37
    truelat1: 55.45
    truelat2: 55.45
    stand_lon: 37.37
    geog_data_path: /path/to/WPS_GEOG/

domains:
    -   parent_id: 1
        parent_grid_ratio: 1
        i_parent_start: 1
        j_parent_start: 1
        e_we: 120
        e_sn: 120
        geog_data_res: default

    -   parent_id: 1
        parent_grid_ratio: 3
        i_parent_start: 40
        j_parent_start: 40
        e_we: 120
        e_sn: 120
        geog_data_res: default

    -   parent_id: 2
        parent_grid_ratio: 3
        i_parent_start: 40
        j_parent_start: 40
        e_we: 120
        e_sn: 120
        geog_data_res: default

