time:
    START_DATE: 2020-01-01_00:00:00
    END_DATE:   2020-01-01_06:00:00
    INTERVAL_SECONDS: 10800

geogrid:
    N_DOMAINS: 1
    DX: 10000
    DY: 10000
    LAT: 55.45
    LON: 37.37
    DATA_PATH: /path/to/WPS_GEOG/

domains:
    -   PARENT_ID: 1
        PARENT_GRID_RATIO: 1
        I_PARENT_START: 1
        J_PARENT_START: 1
        E_WE: 120
        E_SN: 120
        GEOG_DATA_RES: '"default"'

physics:
    MP_PHYSICS: 8
    RA_LW_PHYSICS: 4
    RA_SW_PHYSICS: 4
    RADT: 6
    SF_SFCLAY_PHYSICS: 1
    SF_SURFACE_PHYSICS: 2
    SF_URBAN_PHYSICS: 1
    BL_PBL_PHYSICS: 1
    CU_PHYSICS: 3

dynamics:
    DIFF_6TH_OPT: 0
    DIFF_OPT: 1
    KM_OPT: 4
